"""baseline — schema already created by SQLModel create_db_and_tables()

Revision ID: 465e559af203
Revises:
Create Date: 2026-04-09 09:59:08.733102

This migration is intentionally a no-op. The database schema was bootstrapped
by SQLModel's create_db_and_tables() before Alembic was introduced. All tables
are already in the correct state. Future schema changes should be tracked via
new autogenerated migrations on top of this baseline.
"""
from typing import Sequence, Union

revision: str = "465e559af203"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass  # Schema already exists — nothing to apply.


def downgrade() -> None:
    pass  # Cannot safely drop tables that were not created by this migration.
